### ISSUE TITLE
KeyError: u'profile-collective.prettydate:default'

### ISSUE THREAD

**Issue by teroajk** [collective/collective.twitter.portlets#3]
When trying to activate this in Plone 4.1.4, I got the traceback below. I tried installing collective.prettydate, but the error remains.

<pre>
Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 575, in installProducts
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 498, in installProduct
   - __traceback_info__: ('collective.twitter.portlets',)
  Module Products.ExternalMethod.ExternalMethod, line 234, in __call__
   - __traceback_info__: ((<PloneSite at /MinnaKuusela>,), {'reinstall': False}, (False,))
  Module /home/tero/Plone/buildout-cache/eggs/collective.twitter.portlets-1.0b1-py2.6.egg/collective/twitter/portlets/Extensions/Install.py, line 12, in install
  Module Products.GenericSetup.tool, line 325, in runAllImportStepsFromProfile
   - __traceback_info__: profile-collective.twitter.portlets:default
  Module Products.GenericSetup.tool, line 1059, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1042, in getProfileDependencyChain
  Module Products.GenericSetup.tool, line 1040, in getProfileDependencyChain
  Module Products.GenericSetup.tool, line 825, in getDependenciesForProfile
KeyError: u'profile-collective.prettydate:default'
</pre>

System information:

Plone 4.1.4 (4113)
CMF 2.2.5
Zope 2.13.12
Python 2.6.7 (r267:88850, May 31 2012, 22:30:53) [GCC 4.6.3]
PIL unknown
debug-mode=on

**Comment by hvelarde** [comment]
how are you trying to activate it, from control panel or running the GS profile?

**Comment by teroajk** [comment]
From control panel at prefs_install_products_form.

**Comment by teroajk** [comment]
I did some searching and from here

http://plone.293351.n2.nabble.com/Trouble-installing-Ploneboard-td5000698.html

and some further research, I'd venture a guess that this is caused by the following commit in collective.prettydate:

https://github.com/collective/collective.prettydate/commit/d9601de66f9139c558c3f18b04a8890ed637593a

The commit removes the "default" GS-profile, which collective.twitter.portlets seems to look for.

I'll try downgrading collective.prettydate to 1.0 and see if that fixes the problem for me.

**Comment by teroajk** [comment]
Well, the downgrading was surprisingly hairy, but it's done now. I can confirm that everything works fine with collective.prettydate version 1.0, but the error appears with 1.1.

**Comment by hvelarde** [comment]
you are completely right about this; thanks for pointing out :-)

**Comment by hvelarde** [comment]
@frapell this issue should be affecting other packages as well; please take care of it

**Comment by hvelarde** [comment]
here you go http://pypi.python.org/pypi/collective.twitter.portlets/1.0b2 :-)

**Comment by teroajk** [comment]
Thanks, working smoothly now :)
